apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      key: web-app
  template:
    metadata:
      labels:
        key: web-app
    spec:
      containers:
        - name: test-cont 
          image: muralisocial123/insurance-app-excelr:latest
          ports:
            - containerPort: 80
--- 
apiVersion: v1 
kind: Service
metadata:
  name: example-svc
spec:
  selector:
    key: web-app
  ports:
  - port: 82
    targetPort: 80
  type: LoadBalancer   
            
