apiVersion: v1 
kind: Pod
metadata:
  name: test-pod
  labels:
    name: web
spec:
  containers:
  - name: test-web 
    image: muralisocial123/insurance-app-excelr:latest
    resources:
      limits:
        memory: "250Mi"
        cpu: "100m"
      requests:
        memory: "128Mi"  
        cpu: "50m"
    ports:
      - containerPort: 80
